// Builds the native-speaker audio bank used by the lesson.
//   node tools/build-audio.mjs [path/to/realdata]
// Needs ffmpeg and the recordings fetched by tests/fetch-real-data.py.
//
// For each clip: high-pass 70 Hz (removes the hum in one source), trim silence,
// normalise the peak to -3 dBFS, encode mono 22 kHz 24 kbps MP3. Each clip is then
// run through the game's own detector; `ok` marks clips the detector hears as
// their labelled tone (only those are used as the demo voice).
// Outputs: assets/audio/*.mp3, assets/audio/CREDITS.md, js/data/audioBank.js

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { CONFIG } from '../js/config.js';
import { analyzeUtterance } from '../js/audio/toneClassifier.js';
import { runChain } from '../tests/realdata.mjs';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const data = path.resolve(process.argv[2] || path.join(root, '../realdata'));
const outDir = path.join(root, 'assets/audio');
fs.mkdirSync(outDir, { recursive: true });

// Speakers: A = Chen Wang (syllables), B = public-domain pinyin set, C = Yue Tan (characters)
const SYLLABLES = ['ma', 'ba', 'da', 'yi', 'wu', 'yu', 'shi', 'hao', 'tang', 'guo', 'bao', 'shu', 'gao', 'tian', 'cha', 'qu'];
const CHARS = {
  1: ['天', '书', '高'],
  2: ['麻', '人', '茶', '鱼'],
  3: ['马', '好', '水', '五', '雨'],
  4: ['骂', '大', '去', '是'],
};
const CHAR_SYL = { 天: 'tian', 书: 'shu', 高: 'gao', 麻: 'ma', 人: 'ren', 茶: 'cha', 鱼: 'yu', 马: 'ma', 好: 'hao', 水: 'shui', 五: 'wu', 雨: 'yu', 骂: 'ma', 大: 'da', 去: 'qu', 是: 'shi' };

const list = [];
for (const s of SYLLABLES) {
  for (let t = 1; t <= 4; t++) {
    const a = path.join(data, `audio-cmn/64k/syllabs/cmn-${s}${t}.mp3`);
    const b = path.join(data, `mp3-chinese-pinyin-sound/mp3/${s}${t}.mp3`);
    if (fs.existsSync(a)) list.push({ id: `A-${s}${t}`, sp: 'A', syl: s, tone: t, hanzi: '', src: a });
    if (fs.existsSync(b)) list.push({ id: `B-${s}${t}`, sp: 'B', syl: s, tone: t, hanzi: '', src: b });
  }
}
for (const [t, cs] of Object.entries(CHARS)) {
  for (const c of cs) {
    const f = path.join(data, `audio-cmn/64k/hsk/cmn-${c}.mp3`);
    if (fs.existsSync(f)) list.push({ id: `C-${c}`, sp: 'C', syl: CHAR_SYL[c], tone: Number(t), hanzi: c, src: f });
  }
}

const ff = (args) => execFileSync('ffmpeg', ['-v', 'error', '-y', ...args], { stdio: ['ignore', 'pipe', 'pipe'] });
const trim = 'highpass=f=70,highpass=f=70,silenceremove=start_periods=1:start_threshold=-42dB:start_silence=0.03,areverse,silenceremove=start_periods=1:start_threshold=-42dB:start_silence=0.06,areverse';

const bank = [];
let okCount = 0;
for (const c of list) {
  // Measure the peak after trimming
  let peakDb = 0;
  try {
    const out = execFileSync('sh', ['-c', `ffmpeg -v info -i "${c.src}" -af "${trim},volumedetect" -f null - 2>&1`]).toString();
    const m = out.match(/max_volume:\s*(-?[\d.]+) dB/);
    if (m) peakDb = parseFloat(m[1]);
  } catch (e) { /* keep 0 */ }
  const gain = -3 - peakDb;
  const safe = c.id.replace(/[^\w-]/g, (ch) => `u${ch.codePointAt(0).toString(16)}`);
  const mp3 = path.join(outDir, `${safe}.mp3`);
  ff(['-i', c.src, '-af', `${trim},volume=${gain.toFixed(2)}dB,afade=t=in:d=0.008`, '-ac', '1', '-ar', '22050', '-b:a', '24k', mp3]);

  // Check with the game's own detector (decode the encoded clip, as the browser would)
  const pcm = execFileSync('ffmpeg', ['-v', 'error', '-i', mp3, '-ac', '1', '-ar', '48000', '-f', 'f32le', '-'], { maxBuffer: 1 << 26 });
  const x = new Float32Array(pcm.buffer, pcm.byteOffset, pcm.length / 4);
  const utt = runChain(Float32Array.from(x, (v) => v * 0.6)).sort((a, b) => b.length - a.length)[0];
  const ok = !!utt && analyzeUtterance(utt, c.tone, CONFIG, CONFIG.strictness.standard).status === 'correct';
  if (ok) okCount++;
  const bytes = fs.readFileSync(mp3);
  bank.push({ id: c.id, sp: c.sp, syl: c.syl, tone: c.tone, hanzi: c.hanzi, ok, file: path.basename(mp3), data: bytes.toString('base64') });
}

const header = `// Generated by tools/build-audio.mjs — do not edit by hand.
// Native-speaker recordings of isolated syllables, used by the lesson.
// Speaker A: Chen Wang, Speaker C: Yue Tan — from github.com/hugolpz/audio-cmn, CC BY-SA.
// Speaker B: github.com/davinfifield/mp3-chinese-pinyin-sound, public domain (Unlicense).
// Clips were high-passed, trimmed, peak-normalised and re-encoded (see assets/audio/CREDITS.md).
`;
const body = `export const AUDIO_BANK = [\n${bank.map((b) => `  ${JSON.stringify({ id: b.id, sp: b.sp, syl: b.syl, tone: b.tone, hanzi: b.hanzi, ok: b.ok, data: b.data })},`).join('\n')}\n];\n`;
fs.writeFileSync(path.join(root, 'js/data/audioBank.js'), header + body);

fs.writeFileSync(path.join(outDir, 'CREDITS.md'), `# Audio credits

The lesson's listening exercises use recordings by three native Mandarin speakers.
Every clip was high-passed at 70 Hz, trimmed, peak-normalised to -3 dBFS and
re-encoded as mono 22 kHz MP3. The processed clips are embedded in
\`js/data/audioBank.js\` and also kept here as files.

| Speaker | Files | Source | Licence |
|---|---|---|---|
| A | \`A-*.mp3\` | Chen Wang, syllable recordings, [hugolpz/audio-cmn](https://github.com/hugolpz/audio-cmn) | CC BY-SA |
| B | \`B-*.mp3\` | [davinfifield/mp3-chinese-pinyin-sound](https://github.com/davinfifield/mp3-chinese-pinyin-sound) | Public domain (Unlicense) |
| C | \`C-*.mp3\` | Yue Tan, HSK character recordings, [hugolpz/audio-cmn](https://github.com/hugolpz/audio-cmn) (from the Shtooka project) | CC BY-SA |

The processed clips from A and C are shared under the same CC BY-SA licence.
`);

const kb = (fs.statSync(path.join(root, 'js/data/audioBank.js')).size / 1024).toFixed(0);
console.log(`${bank.length} clips (${okCount} recognised by the detector) → js/data/audioBank.js (${kb} KB)`);
const by = {};
for (const b of bank) by[b.sp] = (by[b.sp] || 0) + 1;
console.log('per speaker', by, 'not recognised:', bank.filter((b) => !b.ok).map((b) => b.id).join(' '));
